#!/bin/bash

#License:
#"Remote Syslog" is a free application what can be used to view syslog messages.
#Copyright (C) 2020 Tom Slenter
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#For more information contact the author:
#Name author: Tom Slenter
#E-mail: info@remotesyslog.com

RSDEST=/opt/RS/plugins
SYSLOGCONF=/etc/syslog-ng/conf.d
GEOCONF=/etc/GeoIP.conf

#Banner
function banner() {
    echo ""
    echo "#################################################"
    echo "#Remote Syslog X/C                              #"
    echo "#More information: remotesyslog.com             #"
    echo "#Remote Syslog plugins                          #"
    echo "#Version: RSX 0.1                               #"
    echo "#Donate XRP: rHdkpJr3qYqBYY3y3S9ZMr4cFGpgP1eM6B #"
    echo "#################################################"
    echo ""
    echo "The plugins are experimental and ONLY tested for RSX ..."
    echo "Use at your own risk ..."
    echo ""
}

#Check if user is root
if ! [ $(id -u) = 0 ]; then
    clear
    banner
    echo "This installation must be run as root!"
    echo ""
    exit 1
fi

#Check if database is corectly installed
function geo_check() {
    if [ -f /usr/share/GeoIP/GeoLite2-City.mmdb ]; then
        echo "Check database for IP: 1.2.3.4 ..."
        mmdblookup --file /usr/share/GeoIP/GeoLite2-City.mmdb --ip 1.2.3.4
        echo "Check done ..."
    else
        echo "No database found ..."
        exit
    fi
}

#Function for geo data
function geo() {
    echo "Install geo data module ..."
    sudo add-apt-repository ppa:maxmind/ppa -y
    apt update
    apt install geoipupdate mmdb-bin syslog-ng-mod-geoip2 -y
    echo ""
    echo ""
    echo "Instuction:"
    echo ""
    echo "Go to https://dev.maxmind.com/geoip/geoipupdate/ and create a account ..."
    echo "After that request a license and then continue ..."
    echo ""
    if [ -f $GEOCONF ]; then
        read -p 'Account ID: ' accountid
        read -p 'LicenseKey: ' licensekey
        if test "$accountid" = ""; then
            echo "Sorry, Account ID cannot be blank" >&2
            exit 1;
        fi
        if test "$licensekey" = ""; then
            echo "Sorry, License Key cannot be blank" >&2
            exit 1;
        fi
        echo "Update configuration ..."
        sed -i "s|\AccountID 0|AccountID $accountid|" $GEOCONF
        sed -i "s|\LicenseKey 000000000000|LicenseKey $licensekey|" $GEOCONF
        echo "Update database..."
        geoipupdate
        echo "Geo configuration updated with:"
        cat $GEOCONF | grep AccountID
        cat $GEOCONF | grep LicenseKey
    else
        echo "Configuration file not found ..."
    fi
}

#Function for geo data update
function geoupdate_rs() {
    if [ -f /usr/share/GeoIP/GeoLite2-City.mmdb ]; then
        echo "Update database... "
        geoipupdate
    else
        echo "No database found ..."
        exit
    fi
}

#Install ubiquiti parser
function ubiquiti_parser() {
    echo "Print config ..."
	cat $RSDEST/99RSX-uni-ubi.conf
	echo ""
	read -p "Do you want to update the default RSX configuration with this one? " -n 1 -r
	echo ""
	if [[ $REPLY =~ ^[Yy]$ ]]
	then
	    echo "Overwrite of default RSX file ..."
	    cp $RSDEST/99RSX-uni-ubi.conf $SYSLOGCONF/99RSX-rs.conf
            echo "Update Elastic configuration ..."
            curl -X POST -H 'Content-Type: application/json' 'http://localhost:9200/rsx-syslog-ng/_mapping' -d \
            '{
               "properties" : {
                  "geoip2" : {
                     "properties" : {
                        "src.geo_point" : {
                           "type" : "geo_point"
                        }
                     }
                  }
               }
            }'
            curl -X POST -H 'Content-Type: application/json' 'http://localhost:9200/rsx-syslog-ng/_mapping' -d \
            '{
               "properties" : {
                  "geoip2" : {
                     "properties" : {
                        "dst.geo_point" : {
                           "type" : "geo_point"
                        }
                     }
                  }
               }
            }'
            echo "Restart services ..."
            service syslog-ng restart
            echo ""
            cat $RSDEST/99RSX-uni-ubi.txt
            echo ""
            echo "Done ..."
            exit
	else
	    echo "Exit ..."
            exit
	fi
}

clear
banner
#Menu
PS3='Please enter your choice: '
options=("Install Geo2 location data" "Update Geo2 location database" "Check Geo2 database" "Install/view ubiquiti/unifi config with Geo2" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Install Geo2 location data")
            clear
            banner
            geo
            exit
    ;;
        "Update Geo2 location database")
            clear
            banner
            geoupdate_rs
            exit
    ;;

        "Check Geo2 database")
            clear
            banner
            geo_check
            exit
    ;;
        "Install/view ubiquiti/unifi config with Geo2")
            clear
            banner
            ubiquiti_parser
            exit
    ;;
        "Quit")
            break
    ;;
        *) echo "Invalid option $REPLY ..." ;;
    esac
done
