#!/bin/bash
#Var
RSDESTP_armubntfix=/opt/RS/plugins/armubntfix

#Check if user is root
if ! [ $(id -u) = 0 ]; then
    echo "This installation must be run as root!"
    echo ""
    exit 1
fi
#Fix
echo "Setup fix ..."
echo "" > /etc/apt/sources.list.d/syslog-ng.list
apt update

exit
